#!/bin/bash
cp ./org.pqrs.Karabiner-Preferences.plist ~/Library/Preferences/org.pqrs.Karabiner-Preferences.plist
cp ./Default\ \(OSX\).sublime-keymap ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap
