#!/bin/bash
cp ~/Library/Preferences/org.pqrs.Karabiner.plist ./karabiner/
cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap ./sublime/
cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings ./sublime/
