#!/bin/bash
cp ~/library/Preferences/org.pqrs.Karabiner.plist ./karabiner/
cp ~/Library/Application\ Support/Karabiner/private.xml ./karabiner/

cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap ./sublime/
cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings ./sublime/

cp ~/Library/Preferences/com.divisiblebyzero.Spectacle.plist ./spectacle/

cp ~/Library/Preferences/com.googlecode.iterm2.plist ./iterm2/
